# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20171123_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
